services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=FinanceStrongPass123!
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  backend:
    build: 
      context: ./FinanceDashboard.API
    restart: always
    depends_on:
      - db
    ports:
      - "127.0.0.1:7145:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=FinanceDb;User Id=sa;Password=FinanceStrongPass123!;TrustServerCertificate=True;
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=TitkosJelszo123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/FinanceDashboard.pfx
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https:ro

  frontend:
    build:
      context: ./FinanceDashboard.UI
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  sqldata: